# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-329affc7-6962-4b74-ade2-4223fbdd2f4c";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-329affc7-6962-4b74-ade2-4223fbdd2f4c".device = "/dev/disk/by-uuid/329affc7-6962-4b74-ade2-4223fbdd2f4c";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/66BD-0867";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-7fd1c891-8a9b-48f6-8107-28f3f524c5d5"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
